# Site settings
title: Old Fart's Elixir Blog
email: scottnelsonsmith@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a recent enthusiast for Elixir.  As a beginner, I want to
  share insights when I discover them; maybe shorten the learning curve for others.
  Enjoy!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scottnelsonsmith.com" # the base hostname & protocol for your site
twitter_username: _ofd
github_username:  oldfartdeveloper
timezone: America/Los_Angeles

# Build settings
markdown: redcarpet
