# Site settings
title: Old Fart's Elixir Blog
email: scottnelsonsmith@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a recent Elixir enthusiast.  As a n00b, I want to
  share insights when I discover them; maybe shorten the learning curve for others.
  Enjoy!
baseurl: "/my_elixir_blog" # the subpath of your site, e.g. /blog
url: "http://scottnelsonsmith.com" # the base hostname & protocol for your site
twitter_username: _ofd
github_username:  oldfartdeveloper
timezone: America/Los_Angeles

# From http://pixelcog.com/blog/2013/jekyll-from-scratch-core-architecture/
include: ['_pages']
relative_permalinks: false

permalink:     '/blog/:year/:title/'
paginate:      10
paginate_path: '/blog/page:num/'

# Build settings
markdown: redcarpet
